# Site settings
title: BY Blog                    # 你的博客网站标题
SEOTitle: 师天下 | @EK Blog		# SEO 标题
description: "Hey"	   	   # 随便说点，描述一下

# SNS settings      
github_username: enkun-li    # 你的github账号
jianshu_username: e71990ada2fd  # 你的简书ID。

# Build settings
# paginate: 10              # 一页你准备放几篇文章

theme: jekyll-theme-cayman